// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHY-cawV60DzQIbS21E7atrU6BAdyVtGg',
    appId: '1:673595653369:web:06cef8e7e7e4d4dfbf7628',
    messagingSenderId: '673595653369',
    projectId: 'bogentrack',
    authDomain: 'bogentrack.firebaseapp.com',
    storageBucket: 'bogentrack.appspot.com',
    measurementId: 'G-QR4TSG9K78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcswvPCvRBYmURwP9DrOravMdWMXdGDJk',
    appId: '1:673595653369:android:011d37fcf38eaf89bf7628',
    messagingSenderId: '673595653369',
    projectId: 'bogentrack',
    storageBucket: 'bogentrack.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX1cOLXbQDWsHWyAkHD53OzMbIkTX22Kc',
    appId: '1:673595653369:ios:69f3feb8f342199dbf7628',
    messagingSenderId: '673595653369',
    projectId: 'bogentrack',
    storageBucket: 'bogentrack.appspot.com',
    iosClientId: '673595653369-ofo0isfmqobpbse0ugiscbclj67o5se9.apps.googleusercontent.com',
    iosBundleId: 'uk.naich.bogenTrack',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX1cOLXbQDWsHWyAkHD53OzMbIkTX22Kc',
    appId: '1:673595653369:ios:69f3feb8f342199dbf7628',
    messagingSenderId: '673595653369',
    projectId: 'bogentrack',
    storageBucket: 'bogentrack.appspot.com',
    iosClientId: '673595653369-ofo0isfmqobpbse0ugiscbclj67o5se9.apps.googleusercontent.com',
    iosBundleId: 'uk.naich.bogenTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWqAd5Mj-9TW4orTTRZiU6iiwIgtD3YWg',
    appId: '1:673595653369:web:1b2c902365f37385bf7628',
    messagingSenderId: '673595653369',
    projectId: 'bogentrack',
    authDomain: 'bogentrack.firebaseapp.com',
    storageBucket: 'bogentrack.appspot.com',
    measurementId: 'G-5ZBSRZ58V6',
  );
}
